 const CartActionTypes = {
    TOOGLE_CART_HIDDEN:'TOOGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    REMOVE_ITEM:'REMOVE_ITEM',
    CLEAR_ITEMS_FROM_CART:'CLEAR_ITEMS_FROM_CART'
};

export default CartActionTypes